### ISSUE TITLE
COPY failed: stat /var/lib/docker/tmp/docker-builder673307680/install.exp: no such file or directory

### ISSUE THREAD

**Issue by bmaciag** [brandoncaulfield/sap-nw-abap-trial-docker-windows#1]
Hi, I get the same error as you in the Youtube video and then its not finishing:
COPY failed: stat /var/lib/docker/tmp/docker-builder673307680/install.exp: no such file or directory

Any suggestions?

**Comment by brandoncaulfield** [comment]
Hi @bmaciag, that error is because a file is missing from the repository called install.exp. It's a file to automate the install process you would manually follow when running ./install.sh. I've included the file in the repo so try wit hthat file there but I don't think thats the main issue as it should still work even if that copy error comes up.

Could you try again with that ./install.exp file included and let me know the results?

**Comment by bmaciag** [comment]
this at least solved this issue. But one more remark: the folder with the files need to be "sapdownloads" not "sapdownload"
